"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CompanyLocationArray_1 = require("./CompanyLocationArray");
var Company_1 = require("./Company");
var Employee_1 = require("../../EuropeanCompany/src/Employee");
var arrayLocation = new CompanyLocationArray_1.CompanyLocationArray();
var company1 = new Company_1.Company(arrayLocation);
var employee1 = new Employee_1.Employee('Employee 1', 'Project 1');
var employee2 = new Employee_1.Employee('Employee 2', 'Project 2');
var employee3 = new Employee_1.Employee('Employee 3', 'Project 3');
company1.add(employee1);
company1.add(employee2);
company1.add(employee3);
console.log('Company 1 Project List:', company1.getProjectList());
console.log('Company 1 Name List:', company1.getNameList());
console.log('Company 1 employee : ', arrayLocation.getCount());
